import test from 'node:test'; import assert from 'node:assert/strict';
import { MemoryConversationStore, resolveConversationState, ConversationState, ContextStrategy } from '../lib/conversation-manager.js';
import { ToolSchemaRegistry } from '../lib/tool-schema-registry.js'; import { ToolExecutionLedger } from '../lib/tool-execution-ledger.js';

test('CASE 1 first Dify request -> BOOTSTRAP',()=>assert.equal(resolveConversationState({messages:[{role:'user'}]}).state,ConversationState.BOOTSTRAP));
test('CASE 2 second round -> CONTINUE and delta',()=>{const r=resolveConversationState({remoteState:{conversationId:'a',valid:true},messages:[{role:'user'}]}); assert.equal(r.state,ConversationState.CONTINUE);assert.equal(r.contextStrategy,ContextStrategy.DELTA_CONTINUE)});
test('CASE 3 Dify A -> OpenAI -> Dify A restores A',()=>{const s=new MemoryConversationStore();s.set('d','dify','a',{conversationId:'A',valid:true});s.set('d','openai','',{conversationId:'O',valid:true});assert.equal(s.get('d','dify','a').conversationId,'A')});
test('CASE 4 Dify A/B independent',()=>{const s=new MemoryConversationStore();s.set('d','dify','a',{conversationId:'A'});s.set('d','dify','b',{conversationId:'B'});assert.equal(s.get('d','dify','a').conversationId,'A');assert.equal(s.get('d','dify','b').conversationId,'B')});
test('CASE 5 unchanged tools -> same hash',()=>{const r=new ToolSchemaRegistry();const a=r.resolve({dshConversationId:'d',providerId:'p',difyAppId:'a',tools:[{type:'function',function:{name:'x',parameters:{b:2,a:1}}}]});const b=r.resolve({dshConversationId:'d',providerId:'p',difyAppId:'a',tools:[{function:{parameters:{a:1,b:2},name:'x'},type:'function'}]});assert.equal(a.toolSchemaHash,b.toolSchemaHash);assert.equal(b.changed,false)});
test('CASE 6 changed tools -> changed hash',()=>{const r=new ToolSchemaRegistry();const a=r.resolve({dshConversationId:'d',providerId:'p',tools:[{function:{name:'x'}}]});const b=r.resolve({dshConversationId:'d',providerId:'p',tools:[{function:{name:'y'}}]});assert.notEqual(a.toolSchemaHash,b.toolSchemaHash)});
test('CASE 7 repeated tool_call executes once',()=>{const l=new ToolExecutionLedger();const i={providerId:'dify',conversationId:'c',toolCallId:'call1',arguments:'{"x":1}'};assert.equal(l.begin(i).replay,false);l.complete(i,'ok');const second=l.begin(i);assert.equal(second.replay,true);assert.equal(second.result,'ok')});
test('CASE 8 tool result -> TOOL_CONTINUE',()=>assert.equal(resolveConversationState({remoteState:{conversationId:'a',valid:true},messages:[{role:'tool',tool_call_id:'c'}]}).state,ConversationState.TOOL_CONTINUE));
test('CASE 9 invalid Dify conversation -> RECOVER',()=>{const r=resolveConversationState({remoteState:{conversationId:'a',valid:false},messages:[]});assert.equal(r.state,ConversationState.RECOVER);assert.equal(r.contextStrategy,ContextStrategy.RECOVERY_BOOTSTRAP)});
test('CASE 10 reset current provider -> next BOOTSTRAP',()=>{const s=new MemoryConversationStore();s.set('d','dify','a',{conversationId:'A'});s.set('d','dify','b',{conversationId:'B'});s.resetProvider('d','dify','a');assert.equal(s.get('d','dify','a'),null);assert.equal(s.get('d','dify','b').conversationId,'B');assert.equal(resolveConversationState({remoteState:null}).state,ConversationState.BOOTSTRAP)});
