import test from 'node:test';
import assert from 'node:assert/strict';
import {
  GuardrailMonitor, GuardrailStatus, PolicyControlPlane, PolicyEvaluation,
  PolicyRegistry, PolicyStatus, PromotionController, stableCanaryBucket,
} from '../packages/dify-core/index.js';
import { resetPolicyRuntimeForTests } from '../lib/policy-runtime.js';
import { selectPolicyForRequest } from '../lib/policy-request.js';

const T0='2026-08-30T04:00:00.000Z', T1='2026-08-30T04:10:00.000Z', T2='2026-08-30T04:20:00.000Z', T3='2026-08-30T04:30:00.000Z', T4='2026-08-30T04:40:00.000Z', T5='2026-08-30T04:50:00.000Z';
function active(version='v1', createdAt=T0, config={}) { return {policyVersion:version,basePolicyVersion:null,candidateId:null,status:PolicyStatus.ACTIVE,config,createdAt,activatedAt:createdAt,rollbackOf:null,evidence:{source:'seed'}}; }
function candidate(id,basePolicyVersion,changes={checkpoint:{backendContextUtilizationThreshold:0.82}},createdAt=T1){return{candidateId:id,basePolicyVersion,changes,evidence:{requestCount:1000},hypothesis:'Deterministic replay supports a canary.',expectedImpact:{tokens:'decrease_predicted'},confidence:'high',createdAt};}
function replayFor(c){return{candidateId:c.candidateId,basePolicyVersion:c.basePolicyVersion,dataset:{datasetId:`dataset-${c.candidateId}`,contentHash:`hash-${c.candidateId}`},risk:{capabilityViolationCount:0,unsupportedDecisionCount:0}};}
const ACCEPTED=Object.freeze({conclusion:PolicyEvaluation.ACCEPT_FOR_CANARY,reasonCodes:Object.freeze(['HARD_GUARDRAILS_PASSED','SOFT_GUARDRAILS_PASSED'])});
function monitor(minimumRequests=2){return new GuardrailMonitor({stages:{[PolicyStatus.CANARY_5]:{minimumRequests,minimumObservationWindowMs:0},[PolicyStatus.CANARY_20]:{minimumRequests,minimumObservationWindowMs:0},[PolicyStatus.CANARY_50]:{minimumRequests,minimumObservationWindowMs:0}}});}
function record(m,policyVersion,timestamp,overrides={}){return m.record({timestamp,policyVersion,success:true,backendPromptTokens:100,completionTokens:10,estimatedCost:1,contextOverflow:false,forcedCompression:false,checkpointCreated:false,toolRequest:true,toolSuccessRate:1,toolRecoveryTriggered:false,fallbackUsed:false,latencyMs:100,firstTokenLatencyMs:20,capabilityViolationCount:0,unsupportedDecisionCount:0,routingDrift:false,...overrides});}
function healthyPair(m,baseline,candidateVersion,timestamp,count=2){for(let i=0;i<count;i++){record(m,baseline,timestamp,{backendPromptTokens:100,estimatedCost:1});record(m,candidateVersion,timestamp,{backendPromptTokens:82,estimatedCost:0.88});}}
function findSession(version,predicate){for(let i=0;i<50000;i++){const session=`session-${i}`;if(predicate(stableCanaryBucket(session,version)))return session;}throw new Error('DETERMINISTIC_CANARY_SESSION_NOT_FOUND');}

test('final E2E: v1 ACTIVE -> v2 full promotion -> v3 hard regression rollback -> all traffic v2',()=>{
  const registry=new PolicyRegistry({policies:[active('v1')]}),m=monitor(),control=new PolicyControlPlane({registry,monitor:m});
  const c2=candidate('candidate-v2','v1');registry.registerReplayPassed({candidate:c2,evaluation:ACCEPTED,replayResult:replayFor(c2),policyVersion:'v2',createdAt:T1});control.promotion.startCanary('v2',{timestamp:T1});
  healthyPair(m,'v1','v2',T1);assert.equal(control.promotion.evaluateAndPromote('v2',{observationEnd:T2}).promotion.targetStage,PolicyStatus.CANARY_20);
  healthyPair(m,'v1','v2',T2);assert.equal(control.promotion.evaluateAndPromote('v2',{observationEnd:T3}).promotion.targetStage,PolicyStatus.CANARY_50);
  healthyPair(m,'v1','v2',T3);assert.equal(control.promotion.evaluateAndPromote('v2',{observationEnd:T4}).promotion.targetStage,PolicyStatus.ACTIVE);
  assert.equal(registry.getActive().policyVersion,'v2');assert.equal(registry.list().filter(p=>p.status===PolicyStatus.ACTIVE).length,1);assert.equal(registry.get('v1').status,PolicyStatus.SUPERSEDED);
  const c3=candidate('candidate-v3','v2',{tool:{pruningConfidenceThreshold:0.60}},T4);registry.registerReplayPassed({candidate:c3,evaluation:ACCEPTED,replayResult:replayFor(c3),policyVersion:'v3',createdAt:T4});control.promotion.startCanary('v3',{timestamp:T4});healthyPair(m,'v2','v3',T4);record(m,'v3',T4,{backendPromptTokens:75,estimatedCost:0.75,toolSuccessRate:0.80});
  const rollback=control.promotion.evaluateAndPromote('v3',{observationEnd:T5});assert.equal(rollback.status,GuardrailStatus.AUTO_ROLLBACK);assert.equal(registry.get('v3').status,PolicyStatus.ROLLED_BACK);assert.equal(rollback.rollback.rollbackTargetPolicy,'v2');assert.equal(registry.getActive().policyVersion,'v2');
  for(let i=0;i<500;i++){const selected=control.selectPolicy({sessionId:`production-${i}`});assert.equal(selected.selectedPolicyVersion,'v2');assert.notEqual(selected.selectedPolicyVersion,'v3');}assert.ok(registry.get('v1'));assert.ok(registry.get('v2'));assert.ok(registry.get('v3'));
});

test('Case A exact metrics: token -18%, cost -12%, error +0.1%, tool success -0.05%, fallback unchanged promotes 5 -> 20',()=>{
  const registry=new PolicyRegistry({policies:[active('v1')]}),c2=candidate('candidate-case-a','v1');registry.registerReplayPassed({candidate:c2,evaluation:ACCEPTED,replayResult:replayFor(c2),policyVersion:'v2',createdAt:T1});const m=monitor(1000),controller=new PromotionController({registry,monitor:m});controller.startCanary('v2',{timestamp:T1});
  for(let i=0;i<1000;i++){record(m,'v1',T1,{backendPromptTokens:100,estimatedCost:1,toolSuccessRate:1,fallbackUsed:false});record(m,'v2',T1,{backendPromptTokens:82,estimatedCost:0.88,success:i!==0,toolSuccessRate:0.9995,fallbackUsed:false});}
  const result=controller.evaluateAndPromote('v2',{observationEnd:T2});assert.equal(result.status,GuardrailStatus.ELIGIBLE_FOR_PROMOTION);assert.equal(result.snapshot.candidateMetrics.requestCount,1000);assert.equal(result.snapshot.candidateMetrics.errorRate-result.snapshot.baselineMetrics.errorRate,0.001);assert.ok(Math.abs((result.snapshot.candidateMetrics.toolSuccessRate-result.snapshot.baselineMetrics.toolSuccessRate)+0.0005)<1e-12);assert.equal(result.snapshot.candidateMetrics.fallbackRate,result.snapshot.baselineMetrics.fallbackRate);assert.ok(Math.abs(result.snapshot.candidateMetrics.backendPromptTokens/result.snapshot.baselineMetrics.backendPromptTokens-0.82)<1e-12);assert.ok(Math.abs(result.snapshot.candidateMetrics.estimatedCost/result.snapshot.baselineMetrics.estimatedCost-0.88)<1e-12);assert.equal(result.snapshot.guardrailResults.promotionEligible,true);assert.equal(result.promotion.targetStage,PolicyStatus.CANARY_20);
});

test('Case D: guardrail evaluator exception blocks canary assignment and fails open to stable ACTIVE',()=>{
  const registry=new PolicyRegistry({policies:[active('v1')]}),c2=candidate('candidate-evaluator-failure','v1');registry.registerReplayPassed({candidate:c2,evaluation:ACCEPTED,replayResult:replayFor(c2),policyVersion:'v2',createdAt:T1});const control=new PolicyControlPlane({registry,monitor:{evaluate(){throw new Error('EVALUATOR_BOOM');}}});control.promotion.startCanary('v2',{timestamp:T1});const session=findSession('v2',b=>b<5);assert.equal(control.selectPolicy({sessionId:session}).selectedPolicyVersion,'v2');const result=control.promotion.evaluateAndPromote('v2',{observationEnd:T2});assert.equal(result.status,GuardrailStatus.EVALUATION_FAILED);assert.ok(result.reasonCodes.includes('GUARDRAIL_EVALUATION_FAILED'));assert.equal(registry.get('v2').status,PolicyStatus.CANARY_5);const selected=control.selectPolicy({sessionId:session});assert.equal(selected.selectedPolicyVersion,'v1');assert.equal(selected.policyAssignment,'STABLE_ACTIVE_FAIL_OPEN');assert.match(selected.selectionFallbackReason,/GUARDRAIL_EVALUATION_FAILED/);
});

test('invalid selected canary config fails open to stable ACTIVE',()=>{
  const registry=new PolicyRegistry({policies:[active('v1')]}),c2=candidate('candidate-invalid-runtime','v1');registry.registerReplayPassed({candidate:c2,evaluation:ACCEPTED,replayResult:replayFor(c2),policyVersion:'v2',createdAt:T1});const control=new PolicyControlPlane({registry,monitor:monitor()});control.promotion.startCanary('v2',{timestamp:T1});const session=findSession('v2',b=>b<5),original=registry.get('v2');registry.policies.set('v2',Object.freeze({...original,config:Object.freeze({tool:{recoveryLimit:99}})}));const selected=control.selectPolicy({sessionId:session});assert.equal(selected.selectedPolicyVersion,'v1');assert.equal(selected.policyAssignment,'STABLE_ACTIVE_FAIL_OPEN');assert.match(selected.selectionFallbackReason,/SELECTED_POLICY_VALIDATION_FAILED/);
});

test('stable bucket and assignment are deterministic across repeated rounds',()=>{
  const registry=new PolicyRegistry({policies:[active('v1')]}),c2=candidate('candidate-stable','v1');registry.registerReplayPassed({candidate:c2,evaluation:ACCEPTED,replayResult:replayFor(c2),policyVersion:'v2',createdAt:T1});const control=new PolicyControlPlane({registry,monitor:monitor()});control.promotion.startCanary('v2',{timestamp:T1});const cs=findSession('v2',b=>b<5),bs=findSession('v2',b=>b>=5),cb=stableCanaryBucket(cs,'v2'),bb=stableCanaryBucket(bs,'v2');for(let i=0;i<100;i++){assert.equal(stableCanaryBucket(cs,'v2'),cb);assert.equal(stableCanaryBucket(bs,'v2'),bb);assert.equal(control.selectPolicy({sessionId:cs}).selectedPolicyVersion,'v2');assert.equal(control.selectPolicy({sessionId:bs}).selectedPolicyVersion,'v1');}
});

test('canary snapshot is immutable and content-addressed deterministically',()=>{
  const m=monitor();healthyPair(m,'v1','v2',T1);const args={policyVersion:'v2',baselinePolicyVersion:'v1',stage:PolicyStatus.CANARY_5,observationStart:T1,observationEnd:T2},first=m.evaluate(args),second=m.evaluate(args);assert.deepEqual(first,second);assert.equal(first.snapshotId,second.snapshotId);assert.equal(first.contentHash,second.contentHash);assert.equal(Object.isFrozen(first),true);assert.equal(Object.isFrozen(first.candidateMetrics),true);record(m,'v2',T1,{backendPromptTokens:70,estimatedCost:0.70});const changed=m.evaluate(args);assert.notEqual(changed.snapshotId,first.snapshotId);assert.notEqual(changed.contentHash,first.contentHash);
});

test('minimum evidence gating keeps healthy candidate in current stage without rollback',()=>{
  const registry=new PolicyRegistry({policies:[active('v1')]}),c2=candidate('candidate-insufficient','v1');registry.registerReplayPassed({candidate:c2,evaluation:ACCEPTED,replayResult:replayFor(c2),policyVersion:'v2',createdAt:T1});const m=monitor(10),controller=new PromotionController({registry,monitor:m});controller.startCanary('v2',{timestamp:T1});healthyPair(m,'v1','v2',T1,3);const result=controller.evaluateAndPromote('v2',{observationEnd:T2});assert.equal(result.status,GuardrailStatus.INSUFFICIENT_CANARY_EVIDENCE);assert.equal(result.snapshot.guardrailResults.promotionEligible,false);assert.equal(registry.get('v2').status,PolicyStatus.CANARY_5);assert.equal(registry.getActive().policyVersion,'v1');
});

test('failed ACTIVE promotion attempt leaves exactly one stable ACTIVE and preserves old policy',()=>{
  const registry=new PolicyRegistry({policies:[active('v1')]}),c2=candidate('candidate-atomic','v1');registry.registerReplayPassed({candidate:c2,evaluation:ACCEPTED,replayResult:replayFor(c2),policyVersion:'v2',createdAt:T1});registry.transition('v2',PolicyStatus.CANARY_5,{timestamp:T1,evaluationSnapshotId:'s1',reasonCodes:['TEST']});registry.transition('v2',PolicyStatus.CANARY_20,{timestamp:T2,evaluationSnapshotId:'s2',reasonCodes:['TEST']});registry.transition('v2',PolicyStatus.CANARY_50,{timestamp:T3,evaluationSnapshotId:'s3',reasonCodes:['TEST']});const validate=registry.validatePolicy.bind(registry);registry.validatePolicy=()=>({valid:false,errors:['INJECTED_PROMOTION_FAILURE']});assert.throws(()=>registry.transition('v2',PolicyStatus.ACTIVE,{timestamp:T4,evaluationSnapshotId:'s4',reasonCodes:['TEST']}),/POLICY_CONFIG_INVALID/);registry.validatePolicy=validate;assert.equal(registry.getActive().policyVersion,'v1');assert.equal(registry.get('v2').status,PolicyStatus.CANARY_50);assert.equal(registry.list().filter(p=>p.status===PolicyStatus.ACTIVE).length,1);assert.ok(registry.get('v1'));
});

test('policy runtime reload failure fails open to cached stable ACTIVE with safety reason',()=>{
  resetPolicyRuntimeForTests();const good={GATEWAY_POLICIES_JSON:JSON.stringify([active('v1')])},req={headers:{'x-session-id':'runtime-session'},body:{}},res={locals:{}};assert.equal(selectPolicyForRequest(req,res,good).selectedPolicyVersion,'v1');const fallbackRes={locals:{}},fallback=selectPolicyForRequest(req,fallbackRes,{GATEWAY_POLICIES_JSON:'{not-json'});assert.equal(fallback.selectedPolicyVersion,'v1');assert.equal(fallback.policyAssignment,'STABLE_ACTIVE_FAIL_OPEN');assert.match(fallback.selectionFallbackReason,/Unexpected token|JSON|position/i);assert.ok(fallbackRes.locals.gatewayGuardrail.reasonCodes.includes('POLICY_RUNTIME_FAIL_OPEN_TO_STABLE_ACTIVE'));resetPolicyRuntimeForTests();
});
