import { MemoryConversationStore } from './conversation-manager.js';
import { ToolSchemaRegistry } from './tool-schema-registry.js';
import { ToolExecutionLedger } from './tool-execution-ledger.js';
import { CheckpointManager, ContextCheckpointStore } from './context-checkpoint.js';
import { RotationRecommendationStore } from './backend-conversation-generation.js';
import { BackendRegistry } from './backend-registry.js';
import { BackendHealthStore } from './backend-health.js';
import { DeterministicBackendRouter } from './backend-router.js';
import { ContextMigrationPlanner } from './context-migration.js';

export const conversationStore = new MemoryConversationStore();
export const checkpointStore = new ContextCheckpointStore();
export const checkpointManager = new CheckpointManager({ store: checkpointStore });
export const rotationRecommendationStore = new RotationRecommendationStore();
export const toolSchemaRegistry = new ToolSchemaRegistry();
export const toolExecutionLedger = new ToolExecutionLedger();
export const backendRegistry = new BackendRegistry();
export const backendHealthStore = new BackendHealthStore();
export const backendRouter = new DeterministicBackendRouter({ registry: backendRegistry, healthStore: backendHealthStore });
export const contextMigrationPlanner = new ContextMigrationPlanner({ checkpointStore });
